### ISSUE TITLE
G-4350 is wrongly reported in a cursor FOR loop with a SQL statement

### ISSUE THREAD

**Issue by deboiph** [Trivadis/plsql-cop-sqldev#10]
Rule G-4350 (Always use 1 as lower and COUNT() as upper bound when looping through a dense array) is wrongly reported in the following code:

   begin
     FOR r_obj IN (
        SELECT obj.object_type, obj.object_name, count(dep.name) cnt
          FROM user_objects obj
          LEFT JOIN user_dependencies dep
            ON dep.type = obj.object_type
           AND dep.name = obj.object_name
         WHERE obj.object_type in ('TYPE', 'TYPE BODY')
         GROUP BY obj.object_TYPE, obj.object_NAME
         ORDER BY cnt
     )
     LOOP
        NULL;
     END LOOP;
   end test;

No array is explicitly used in that code. The issue seems to be linked to this specific SQL query. It disappears when the query is simplified (e.g. SELECT table_name FROM user_tables).

The code to reproduce the problem can be find in the attached file.

[deboiph.zip](https://github.com/Trivadis/plsql-cop-sqldev/files/6130935/deboiph.zip)

**Comment by PhilippSalvisberg** [comment]
It's a bug. I've open Jira ticket PLSQLCOP-311. It looks like it's working only when referencing a cursor. 

I will update this issue when we have fixed this issue.

**Comment by PhilippSalvisberg** [comment]
bug is still open in https://github.com/Trivadis/plsql-cop-cli/releases/tag/v4.0.3

**Comment by PhilippSalvisberg** [comment]
fixed in https://github.com/Trivadis/plsql-cop-cli/releases/tag/v4.1.3
