### ISSUE TITLE
New Trivadis Guidelines G-3195, G-3310 not implemented?

### ISSUE THREAD

**Issue by mhoys** [Trivadis/plsql-cop-sqldev#12]
Hi,
Is it correct that a number of new guidelines in the Trivadis Guidelines 4.0 are not yet implemented in the latest versions of the dbCODECOP plug-in for SQL Developer and SonarQube? I tried for example to check G-3310 with the dbCODECOP plug-in version 4.1 for SQL Developer and the check is not working, is this as expected?
Is there a roadmap for when all the new guidelines will be available in the plug-ins?

Thanks
Matthias

**Comment by PhilippSalvisberg** [comment]
> Is it correct that a number of new guidelines in the Trivadis Guidelines 4.0 are not yet implemented in the latest versions of the dbCODECOP plug-in for SQL Developer and SonarQube?

Yes. See https://github.com/Trivadis/plsql-cop-cli/blob/v4.1.3/validator-limitations.md#g-3310-never-commit-within-a-cursor-loop

> Is there a roadmap for when all the new guidelines will be available in the plug-ins?

In the next version we will include checks for guidelines introduced in 4.0. However, there will always be some guidelines that are not implemented. These limitations are documented per version.

**Comment by mhoys** [comment]
Ok, thanks Philipp!
