### ISSUE TITLE
E-0002 Synatx error 

### ISSUE THREAD

**Issue by S-Koell** [Trivadis/plsql-cop-sqldev#15]
Hi there :)

I have a plsql package where the checker is getting MANY syntax errors. I am providing you with the first one, if you need more code to analyze let me know.

First line here is line 32 in the original
```
 co_scale_unset_target_weight CONSTANT VARCHAR2(100 CHAR)  := co_scale_set_weight_tol || apex_escape.json(' 0 "" ""'); --escaping of json needed because of "

   co_scale_unset_upper_tol     CONSTANT VARCHAR2(100 CHAR)  := co_scale_set_weight_tol || apex_escape.json(' 1 "" ""');
   co_scale_unset_lower_tol     CONSTANT VARCHAR2(100 CHAR)  := co_scale_set_weight_tol || apex_escape.json(' 2 "" ""');

```

<html xmlns="#DEFAULT" xs="http://www.w3.org/2001/XMLSchema">
  <body>
    

Issue# | Line | Severity | Message | Code Excerpt
-- | -- | -- | -- | --
1 | 32 | Blocker | E-0002: Syntax error. Please contact the author if the code compiles            successfully in your environment. | mismatched input '\|' expecting ';'
2 | 32 | Blocker | E-0002: Syntax error. Please contact the author if the code compiles            successfully in your environment. | no viable alternative at input '.'
3 | 32 | Blocker | E-0002: Syntax error. Please contact the author if the code compiles            successfully in your environment. | no viable alternative at input '('
4 | 32 | Blocker | E-0002: Syntax error. Please contact the author if the code compiles            successfully in your environment. | no viable alternative at input '' 0 "" ""''
5 | 32 | Blocker | E-0002: Syntax error. Please contact the author if the code compiles            successfully in your environment. | no viable alternative at input ';'

  </body>
</html>

**Comment by S-Koell** [comment]
Another example (from legacy code!!):

```
funcion xyz is
  ignore exception;
begin
```

<html xmlns="#DEFAULT" xs="http://www.w3.org/2001/XMLSchema">
  <body>
    

1 | 1,404 | Blocker | E-0002: Syntax error. Please contact the author if the code compiles            successfully in your environment. | mismatched input 'ignore' expecting 'begin'
-- | -- | -- | -- | --



  </body>
</html>

and after that of course a lot of stuff where "ignore" is being used.

**Comment by PhilippSalvisberg** [comment]
I cannot reproduce the the problem. I have to use a complete code. That's what I used:

```sql
create package pkg is
   co_scale_unset_target_weight CONSTANT VARCHAR2(100 CHAR)  := co_scale_set_weight_tol || apex_escape.json(' 0 "" ""'); --escaping of json needed because of "

   co_scale_unset_upper_tol     CONSTANT VARCHAR2(100 CHAR)  := co_scale_set_weight_tol || apex_escape.json(' 1 "" ""');
   co_scale_unset_lower_tol     CONSTANT VARCHAR2(100 CHAR)  := co_scale_set_weight_tol || apex_escape.json(' 2 "" ""');
end;
```

Here's the result as screenshot:

![image](https://user-images.githubusercontent.com/3883171/153383009-e7a4d9b1-aed6-482a-9773-9e9666ac79dc.png)

Your second example is simply wrong. Typo in `funcion` and the statement is not properly terminated. Even when it is legacy code it cannot work.

Could you please provide full examples so I can reproduce the problem? Thank you.

**Comment by PhilippSalvisberg** [comment]
Furthermore. Every Syntax issue is worth a dedicated ticket. Thank you.

**Comment by PhilippSalvisberg** [comment]
Closed due to inactivity.
