### ISSUE TITLE
db* CODECOP does not open

### ISSUE THREAD

**Issue by sarismejiasanchez** [Trivadis/plsql-cop-sqldev#16]
Hello!

I was testing the extension and encountered the following error:

db* CODECOP does not open in SQL Developer Version 21.4.3.063

**Comment by PhilippSalvisberg** [comment]
The extension is supposed to work with SQL Developer 21.4.3. I've tested it successfully under Windows and macOS.

Can you please provide the following screen shots of your "About Oracle SQL Developer" dialog?

### Version
![image](https://user-images.githubusercontent.com/3883171/181649263-89c1e496-dcfe-4708-8301-a984417fef17.png)

### Extensions (searching "db*")
![image](https://user-images.githubusercontent.com/3883171/181649098-d01ece7c-6f9b-4139-9d3d-288f84847d35.png)

And then please describe step by step what you did in order for us to reproduce your problem. Thank you.

**Comment by sarismejiasanchez** [comment]
Hello! Thanks for the prompt response.

Sending information requested

**Version**
![image](https://user-images.githubusercontent.com/93800332/181650802-48a96a62-aa6b-40d2-b2f6-23a59a5cc50e.png)

**Extensions (searching "db*")**
![image](https://user-images.githubusercontent.com/93800332/181651648-c568eb4e-514f-4f55-a9e7-68d38b54223c.png)


Right click, select the Check option from the menu
![image](https://user-images.githubusercontent.com/93800332/181651119-e09d5cd6-7ba8-4b35-919a-9a65e934ad82.png)

However, the db* CODECOP is not displayed anywhere on the screen.

Thank you.

**Comment by PhilippSalvisberg** [comment]
Thank you for providing the requested information. So I see the extension is installed and fully loaded. That's good.

You're right, after selecting "Check" from the context menu the "db* CODECOP" window should be shown at the bottom of SQL Developer like here:

![image](https://user-images.githubusercontent.com/3883171/181655878-7f9ced0f-a5de-4426-85fa-f6481adaa361.png)

SQL Developer caches (saves) some Window settings and in some situation this prohibits to re-instantiate a window. The solution is to call "Reset Windows To Factory Settings" from the Window menu. See example below:

![image](https://user-images.githubusercontent.com/3883171/181656061-08502d26-e751-4cfa-a3b4-7dacb87a9a9a.png)

You can call that without losing data. What you lose are the your favorite positions of the Windows within SQLDev. However, it should solve your problem and the "db* CODECOP" window should show up after calling "Check".

Please let us now if this helped.

Thanks.

**Comment by sarismejiasanchez** [comment]
Magnificent! 

Resetting Windows to Factory Settings has solved the problem!

![image](https://user-images.githubusercontent.com/93800332/181777951-577a01b5-dbcd-499b-ab2b-e66232221d50.png)

Thank you very much!
