### ISSUE TITLE
E-0002: Syntax error using non ASCII characters

### ISSUE THREAD

**Issue by notdodgeball** [Trivadis/plsql-cop-sqldev#19]
![image_2023-08-02_152342881](https://github.com/Trivadis/plsql-cop-sqldev/assets/99600325/9f2ff910-b19e-42c1-a1d4-697c14e7dd8b)

use case:
```
create or replace PACKAGE TEST AS
FUNCTION ÓRGÃO      (P_N IN NUMBER) RETURN VARCHAR2;
FUNCTION AVANÇO     (P_N IN NUMBER) RETURN VARCHAR2;
END TEST;
```

Parameters:
```
SELECT PARAMETER, VALUE FROM V$NLS_PARAMETERS WHERE PARAMETER IN ('NLS_CHARACTERSET','NLS_LANGUAGE')

NLS_LANGUAGE	        ENGLISH
NLS_CHARACTERSET	WE8MSWIN1252
```

The package compiles normally. I could not find anything about it [in the docs](https://github.com/Trivadis/plsql-cop-cli/blob/main/parser-limitations.md).

**Comment by PhilippSalvisberg** [comment]
Thank you @notdodgeball for reporting this issue.

The current version of the parser supports only the following characters in identifiers:

First position:

- `a` to `z`
- `A` to `Z`

Position 2ff:

- `a` to `z`
- `A` to `Z`
- `0` to `9` 
- `_`
- `$`
- `#`
- `ä`/`Ä`
- `ö`/`Ö`
- `ü`/`Ü`

I try to use identifiers that follow this scheme, and I avoid the use of `äÄöÖüÜ` (it's supported to successfully parse some legacy code of db* CODECOP customers).

However, the current version of the Oracle Database supports much more letters as you pointed out. In [this blog post](https://www.salvis.com/blog/2022/10/11/quoted-identifiers-joelkallmanday/#consists-of-valid-characters) I explained what identifiers that do not need to be put in double-quotes. The valid scope depends on the character set. For db* CODECOP. the character set of the file is relevant. And identifying the character set is not that easy. It typically needs some guessing with the help of tools like [Apache Tika](https://tika.apache.org/1.27/api/org/apache/tika/parser/txt/CharsetDetector.html).

I accept this as a bug. We will for sure document it as a limitation if we are not going to fix the parser to support all letters within unquoted identifiers. And we need to fix the error message, which should mention the [parser limitations](https://github.com/Trivadis/plsql-cop-cli/blob/main/parser-limitations.md).

As a workaround, you can use quoted identifiers. Here's the rewritten example of your code snippet:

```sql
CREATE OR REPLACE PACKAGE TEST AS
   FUNCTION "ÓRGÃO"      (P_N IN NUMBER) RETURN VARCHAR2;
   FUNCTION "AVANÇO"     (P_N IN NUMBER) RETURN VARCHAR2;
END TEST;
```
