### ISSUE TITLE
Clarification on Non-Commercial Use of db* CODECOP for SQL Developer for Internal Systems in a Retail Company

### ISSUE THREAD

**Issue by horiuchi0704** [Trivadis/plsql-cop-sqldev#25]
Hello,

I work for a retail company, which is a for-profit organization. We are considering using db* CODECOP for SQL Developer in our company, specifically for developing internal systems that will be used only by our employees. We are not selling or distributing this software externally, nor are we charging any usage fees for it, either internally or externally.

I understand that the project is licensed under the Creative Commons Attribution-NonCommercial-NoDerivs 3.0 Unported License (CC BY-NC-ND 3.0), and I want to ensure we're interpreting the terms correctly for our specific use case.

### Question:
Could you please clarify the definition of "non-commercial" in the context of this license? Specifically:

Is it permissible to use db* CODECOP for SQL Developer as a tool in our internal development process for creating in-house systems, even though our company is a for-profit retail business? We want to emphasize that we're not selling the tool or any software developed with it, nor are we charging any fees for its use, either within our company or to external parties. We are solely using it to develop software for our internal operations.

I appreciate your time in clarifying this point. Your response will help ensure we use db* CODECOP for SQL Developer in compliance with its licensing terms.

Thank you for your assistance and for maintaining this valuable tool.

Best regards,
HH4em

**Comment by PhilippSalvisberg** [comment]
You may use db* CODECOP for SQL Developer to build commercial products. However, you may not make it part of your products.

> Is it permissible to use db* CODECOP for SQL Developer as a tool in our internal development process for creating in-house systems, even though our company is a for-profit retail business? We want to emphasize that we're not selling the tool or any software developed with it, nor are we charging any fees for its use, either within our company or to external parties. We are solely using it to develop software for our internal operations.

Yes, you may use it for this purpose.

I hope this answers your question.

**Comment by horiuchi0704** [comment]
Dear PhilippSalvisberg,

Thank you very much for your prompt and clear response to my inquiry about using db* CODECOP for SQL Developer. Your answer has provided the clarification we needed regarding the non-commercial use of the tool in our for-profit retail company.
The information you've provided is sufficient and helps us ensure that our intended use of db* CODECOP for SQL Developer for internal development purposes is in compliance with the licensing terms.
We appreciate your time and effort in addressing our concerns. Your response has been extremely helpful, and we now consider this matter closed.
Thank you once again for maintaining this valuable tool and for your assistance.

Best regards,
HH4em
