### ISSUE TITLE
Confirmation: No External Data Transmission by plsql-cop-sqldev

### ISSUE THREAD

**Issue by horiuchi0704** [Trivadis/plsql-cop-sqldev#26]
Hello

Is my understanding correct that CODECOP operates completely standalone without sending any information externally when used?

For context, I believe CODECOP does not transmit data externally. 
However, my company requires explicit confirmation from the developers on this matter, which is why I'm asking this question.

BR,
Hh4em

**Comment by PhilippSalvisberg** [comment]
> Is my understanding correct that CODECOP operates completely standalone without sending any information externally when used?

Correct.

**Comment by horiuchi0704** [comment]
Thank a lot!!
