### ISSUE TITLE
G-3120 reported when USER is selected from a join query

### ISSUE THREAD

**Issue by deboiph** [Trivadis/plsql-cop-sqldev#7]
Rule ~~G-2330~~ G-3120 (Always use table aliases when your SQL statement involves more than one source) is reported as violated on the following query:

     SELECT USER, ind.index_name, tab.table_name
       FROM user_indexes ind
      INNER JOIN user_tables tab
         ON tab.table_name = ind.table_name

More precisely, the error is reported on the USER function because it is not qualified by a table alias. In reality, it should not be and it cannot be. No problem is reported with other functions like SYSDATE.

The above query has been written just for the purpose of reporting this issue so no need to say it's completely useless.

A package (spec & body) containing the above query is attached below.

[trivadis_test.zip](https://github.com/Trivadis/plsql-cop-sqldev/files/6129387/trivadis_test.zip)

Thanks

**Comment by PhilippSalvisberg** [comment]
Thanks for reporting this issue. I guess you meant [G-3120](https://trivadis.github.io/plsql-and-sql-coding-guidelines/v4.0/4-language-usage/3-dml-and-sql/1-general/g-3120/).

It's a bug. All pseudo columns and all parameterless functions need to be ignored. Some are ignored (such as `SYSDATE` as you mentioned), but the list is incomplete.

I've created a Jira ticket PLSQLCOP-309 for this issue and will update this issue when it is fixed.

**Comment by deboiph** [comment]
Yes, I meant G-3120, not 2330, sorry!

I saw this bug only for USER but other functions might be concerned as well, indeed.

Thanks for your follow-up.

**Comment by PhilippSalvisberg** [comment]
bug is still open in https://github.com/Trivadis/plsql-cop-cli/releases/tag/v4.0.3

**Comment by PhilippSalvisberg** [comment]
fixed in https://github.com/Trivadis/plsql-cop-cli/releases/tag/v4.1.3
