### ISSUE TITLE
Questions: when will guidelines v4.0 be supported by the tools?

### ISSUE THREAD

**Issue by deboiph** [Trivadis/plsql-cop-sqldev#8]
I just saw that a new version of the guidelines (v4.0) has been recently published.
I guess that you are currently working to update the tools (CLI and plugins).
Do you know approximatively when they will be made available?

**Comment by PhilippSalvisberg** [comment]
It's planned to release it per end of this month... no guarantees. Priority has the new grammar (21c) and the new SonarQube plugin which does not rely on the CLI anymore.

4.0 comes with 19 new guidelines. Checks will be provided a bit later, but the guidelines will be part of the CLI and SonarQube and all links will be updated.

**Comment by deboiph** [comment]
Thanks for sharing your plan.
